apiVersion: v1
kind: Pod
metadata:
  name: crawler_worker
  namespace: lab18
spec:
  containers:
  - name: crawler_worker
    image: ubuntu:20.04
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
    command:
      - "sleep"
      - "infinity"
    volumeMounts:
      - name: history-dir
        mountPath: /var/log/history
  volumes:
  - name: history-dir
    persistentVolumeClaim:
      claimName: pvc-lab18