apiVersion: v1
kind: Service
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  type: NodePort
  selector:
    app: api-server
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
